// <auto-generated />
using System;
using API_PRODUCAO.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API_PRODUCAO.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API_PRODUCAO.Models.Cadastro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodBarra")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodProduto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Maquina")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PesoBruto")
                        .HasColumnType("float");

                    b.Property<double>("PesoLiquido")
                        .HasColumnType("float");

                    b.Property<double>("PesoTotalPalete")
                        .HasColumnType("float");

                    b.Property<string>("Produto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QtdeCaixa")
                        .HasColumnType("int");

                    b.Property<int>("QtdePorPalete")
                        .HasColumnType("int");

                    b.Property<string>("Unidade")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cadastros");
                });

            modelBuilder.Entity("API_PRODUCAO.Models.DetalhamentoOP", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EmbPerdidas")
                        .HasColumnType("int");

                    b.Property<int>("EmbProcessadas")
                        .HasColumnType("int");

                    b.Property<int>("EmbProduzidas")
                        .HasColumnType("int");

                    b.Property<string>("Operador")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrdemProducao")
                        .HasColumnType("int");

                    b.Property<string>("Turno")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OrdemProducao");

                    b.ToTable("DetalhamentoOPs");
                });

            modelBuilder.Entity("API_PRODUCAO.Models.Eficiencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Motivo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Operador")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrdemProducao")
                        .HasColumnType("int");

                    b.Property<int?>("ProducoesOrdemProducao")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("Tempo")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("ProducoesOrdemProducao");

                    b.ToTable("Eficiencia");
                });

            modelBuilder.Entity("API_PRODUCAO.Models.Paletizacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bloqueio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodigoProduto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataHoraPaletizacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Maquina")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("N_Palete")
                        .HasColumnType("int");

                    b.Property<int>("OrdemProducao")
                        .HasColumnType("int");

                    b.Property<int?>("ProducoesOrdemProducao")
                        .HasColumnType("int");

                    b.Property<string>("Produto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QtdeCx")
                        .HasColumnType("int");

                    b.Property<int>("QtdePorPalete")
                        .HasColumnType("int");

                    b.Property<int>("QtdeProduzida")
                        .HasColumnType("int");

                    b.Property<string>("Unidade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Usuario")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProducoesOrdemProducao");

                    b.ToTable("Paletizacoes");
                });

            modelBuilder.Entity("API_PRODUCAO.Models.Perdas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Motivo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Operador")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrdemProducao")
                        .HasColumnType("int");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrdemProducao");

                    b.ToTable("Perdas");
                });

            modelBuilder.Entity("API_PRODUCAO.Models.Producoes", b =>
                {
                    b.Property<int>("OrdemProducao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrdemProducao"));

                    b.Property<DateTime>("DataHoraAbertura")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataHoraFechamento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Maquina")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Produto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unidade")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OrdemProducao");

                    b.ToTable("Producoes");
                });

            modelBuilder.Entity("API_PRODUCAO.Models.Usuarios", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cargo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Matricula")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("API_PRODUCAO.Models.DetalhamentoOP", b =>
                {
                    b.HasOne("API_PRODUCAO.Models.Producoes", "Producao")
                        .WithMany("DetalhamentoOPs")
                        .HasForeignKey("OrdemProducao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producao");
                });

            modelBuilder.Entity("API_PRODUCAO.Models.Eficiencia", b =>
                {
                    b.HasOne("API_PRODUCAO.Models.Producoes", null)
                        .WithMany("Eficiencia")
                        .HasForeignKey("ProducoesOrdemProducao");
                });

            modelBuilder.Entity("API_PRODUCAO.Models.Paletizacao", b =>
                {
                    b.HasOne("API_PRODUCAO.Models.Producoes", null)
                        .WithMany("Paletizacoes")
                        .HasForeignKey("ProducoesOrdemProducao");
                });

            modelBuilder.Entity("API_PRODUCAO.Models.Perdas", b =>
                {
                    b.HasOne("API_PRODUCAO.Models.Producoes", "Producao")
                        .WithMany("Perdas")
                        .HasForeignKey("OrdemProducao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producao");
                });

            modelBuilder.Entity("API_PRODUCAO.Models.Producoes", b =>
                {
                    b.Navigation("DetalhamentoOPs");

                    b.Navigation("Eficiencia");

                    b.Navigation("Paletizacoes");

                    b.Navigation("Perdas");
                });
#pragma warning restore 612, 618
        }
    }
}
